import type { Metadata } from "next";
import Background from "@/components/Background";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=DM+Sans:opsz,wght@9..40,900&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        {children}
        <Toaster position="bottom-right" toastOptions={{
          className: 'bg-white border-2 border-border text-foreground font-base shadow-shadow',
          descriptionClassName: 'text-muted-foreground font-medium',
          classNames: {
            actionButton: 'bg-main text-main-foreground font-bold border-2 border-border shadow-sm hover:shadow-none',
          }
        }} />
      </body>
    </html>
  );
}
