import type { Metadata } from "next";
import Background from "@/components/Background";
import { DM_Sans, Bagel_Fat_One } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["900"],
});

const bagel = Bagel_Fat_One({
  variable: "--font-bagel-fat-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${bagel.variable} antialiased`}>
        <div className="fixed inset-0 -z-10">
          <Background
            speed={0.05}
            direction="diagonal"
            borderColor="#624722"
            hoverFillColor="#444"
            squareSize={120}
            lineWidth={5}
            backgroundColor="#f5c5be"
          />
        </div>
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
