import type { Metadata } from "next";
import Background from "@/components/Background";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,700;9..40,900&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        {children}
        <Toaster
          position="bottom-right"
          theme="light"
          toastOptions={{
            unstyled: true,
            classNames: {
              toast: 'bg-background border-2 border-border text-foreground font-base shadow-shadow p-4 flex gap-3 items-center w-full md:w-[356px] rounded-base',
              title: 'font-heading text-lg leading-tight',
              description: '!text-foreground text-sm font-bold',
              actionButton: 'bg-main text-main-foreground text-sm font-bold border-2 border-border shadow-sm hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-none transition-all px-3 py-1.5 rounded-base shrink-0',
            }
          }}
        />
      </body>
    </html>
  );
}
